---
- name: Add objects to firewall
  hosts: all
  connection: local
  gather_facts: False
  
  vars:
    credentials:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      
  roles:
  - role: PaloAltoNetworks.paloaltonetworks
    
  tasks:
  - name: create an address object
    panos_address_object:
      provider: '{{ credentials }}'
      name: '{{ object_name }}'
      value: '{{ object_value }}'
      description: '{{ object_description }}'
      state: 'present'
      commit: False
