---
- name: Commit hack on Panorama
  hosts: all
  connection: local
  gather_facts: False

  vars:
    commit_cmd: "{{ commit_cmd }}"
    credentials:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

  roles:
    - role: paloaltonetworks.paloaltonetworks

  tasks:
    - name: retrieve api_key
      panos_api_key:
        provider: "{{ credentials }}"
      register: auth

    - name: Commit via URI
      uri:
        url: "https://{{ ip_address }}/api?key={{ auth.api_key }}&type=commit&action=all&cmd={{ commit_cmd | urlencode }}"
        method: POST
        validate_certs: no
