---
- name: Generate a certificate
  hosts: all
  connection: local
  gather_facts: False

  vars:
    credentials:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"      

  collections:
    - paloaltonetworks.panos
    
  tasks:
    - name: Create the certificate signing request
      panos_op:
        provider: "{{ credentials }}"
        cmd: |
          <request>
            <certificate>
              <generate>
                <certificate-name>{{ cert_name }}</certificate-name>
                <name>{{ cert_fqdn }}</name>
                <algorithm>
                  <RSA>
                    <rsa-nbits>2048</rsa-nbits>
                  </RSA>
                </algorithm>
                <digest>sha256</digest>
                <ca>no</ca>
                <signed-by>external</signed-by>
              </generate>
            </certificate>
          </request>
        cmd_is_xml: true
        
    - name: retrieve api_key
      panos_api_key:
        provider: '{{ credentials }}'
      register: api
        
    - name: Export the certificate signing request
      uri:
        url: https://{{ ip_address }}/api?key={{ api.api_key }}&type=export&category=certificate&certificate-name={{ cert_name|urlencode }}&format=pkcs10&include-key=no
        method: POST
        validate_certs: no
        return_content: yes
      register: csr
      failed_when: "'error' in csr.content"
      
    - name: Dump the CSR
      debug:
        var: csr.content
