---
- name: Create/update/delete a service object
  hosts: all
  connection: local
  gather_facts: False
  any_errors_fatal: true

  vars:
    credentials:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

  roles:
    - role: paloaltonetworks.paloaltonetworks

  tasks:
    - name: Process the service object
      panos_service_object:
        provider: "{{ credentials }}"
        device_group: "{{ service_devicegroup }}"
        name: "{{ service_name }}"
        description: "{{ service_description }}"
        protocol: "{{ service_protocol }}"
        destination_port: "{{ service_destination_port }}"
        # tag: ["{{ service_tags }}"]
        commit: False
