---
- name: Load a PAN-OS configuration from XML
  hosts: all
  connection: local
  gather_facts: False

  vars:
    credentials:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
  vars_files:
    - my_vars.yml
      
  roles:
    - role: paloaltonetworks.paloaltonetworks

  tasks:      
  - name: Push the configuration snippet
    vars:
      xml_snippet: "{{ lookup('template', '{{ playbook_dir }}/files/my_config.xml') }}"
    panos_type_cmd:
      provider: '{{ credentials }}'
      cmd: 'set'
      xpath: '{{ xpath }}'
      element: '{{ xml_snippet }}'
