---
- name: Load a PAN-OS configuration snippet
  hosts: all
  connection: local
  gather_facts: False

  vars:
    credentials:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      
  roles:
    - role: paloaltonetworks.paloaltonetworks

  tasks:
  - name: Pull the latest templates
    git:
      repo: 'https://github.com/PaloAltoNetworks/iron-skillet.git'
      dest: '{{ playbook_dir }}/files'
      
  - name: Push the configuration snippet
    vars:
      xml_snippet: "{{ lookup('template', 'files/templates/panorama/snippets/{{ snippet_file }}') }}"
    panos_type_cmd:
      provider: '{{ credentials }}'
      cmd: 'set'
      xpath: '{{ xpath }}'
      element: '{{ xml_snippet }}'
