- name: Network Playbook
  hosts: prismacloud
  gather_facts: false
  collections:
    - paloaltonetworks.prismacloud
  tasks:
  - name: Get account list
    prismacloud_cloud_account_facts:
      details: false
      cloud_type: 'gcp'
    register: one
  - debug:
      msg: '{{ one.listing }}'
  - name: Get account groups
    prismacloud_account_group_facts:
    register: ans
  - debug:
      msg: '{{ ans }}'

