---
- name: Process a new tenant
  hosts: all
  connection: local
  gather_facts: False

  vars:
    credentials:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"
    tenant: "{{ tenant_name | replace(' ', '-') | lower }}"

  roles:
    - role: paloaltonetworks.paloaltonetworks

  tasks:
    - name: active directory group
      win_domain_group:
        domain_username: "{{ domain_user }}"
        domain_password: "{{ domain_password }}"
        domain_server: "{{ domain_controller }}"
        name: "{{ tenant_name }}"
        description: "{{ tenant_name }} users"
        organizational_unit: "OU=Firewall Management,DC=PANLABS,DC=org"
        scope: global
        category: security

    - name: ansible tag
      panos_tag_object:
        provider: "{{ credentials }}"
        name: "ansible"
        color: "gold"
        comments: "Added by Ansible"
        commit: False

    - name: tenant address object
      panos_address_object:
        provider: "{{ credentials }}"
        name: "{{ tenant }}-subnet"
        value: "{{ tenant_subnet | ipaddr }}"
        description: "Subnet for {{ tenant_name }}"
        tag: ["ansible"]
        commit: False

    - name: tenant static route
      panos_static_route:
        provider: "{{ credentials }}"
        name: "{{ tenant }}-route"
        virtual_router: default
        destination: "{{ tenant_subnet | ipaddr }}"
        nexthop: "{{ tenant_nexthop | ipaddr }}"
        nexthop_type: ip-address
        metric: 10

    - name: tenant security rule
      panos_security_rule:
        provider: "{{ credentials }}"
        rule_name: "Allow {{ tenant }}"
        description: "Allow access to {{ tenant_name }} sandbox"
        source_zone: ["outside"]
        source_ip: ["any"]
        source_user: ["werum\\{{ tenant_name }}"]
        destination_zone: ["sandboxes"]
        destination_ip: ["{{ tenant }}-subnet"]
        application: ["ping", "ssh"]
        service: ["application-default"]
        action: "allow"
        antivirus: "default"
        vulnerability: "strict"
        spyware: "strict"
        wildfire_analysis: "default"
        tag_name: ["ansible"]
        commit: False

    - name: commit changes
      panos_commit:
        provider: "{{ credentials }}"
      register: commit_output
      debug:
        msg: commit_output
