---
- name: Add security rule to firewall
  hosts: all
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: add a security rule
    panos_security_rule:
      ip_address: '{{ ip_address }}'
      api_key: '{{ api_key }}'
      rule_name: '{{ rule_name }}'
      description: '{{ rule_description }}'
      source_zone: ['{{ rule_source_zone }}']
      destination_zone: ['{{ rule_destination_zone }}']
      source_ip: ['{{ rule_source_ip }}']
      source_user: ['{{ rule_source_user }}']
      destination_ip: ['{{ rule_destination_ip }}']
      category: ['{{ rule_url_category }}']
      application: ['{{ rule_application }}']
      service: ['{{ rule_service }}']
      hip_profiles: ['{{ rule_hip_profile }}']
      action: '{{ rule_action }}'
      state: '{{ rule_state }}'
      commit: False
