- name: Add Firewall Rule
  hosts: all
  connection: local
  gather_facts: false

  roles:
    - role: paloaltonetworks.paloaltonetworks

  vars:
    credentials:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

  tasks:
    # - name: Grab the credentials from ansible-vault
    #   include_vars: "vars.yml"
    #   no_log: "true"

    - name: Create tag for Deny
      panos_tag_object:
        provider: "{{ credentials }}"
        name: "Deny"
        color: "red"
        comments: "Prod Environment"
        commit: False

    - name: Create tag for Web Access
      panos_tag_object:
        provider: "{{ credentials }}"
        name: "Web Access"
        color: "green"
        comments: "Prod Environment"
        commit: False

    - name: setup security profile group
      panos_pg:
        provider: "{{ credentials }}"
        pg_name: "default"
        virus: "default"
        vulnerability: "default"
        spyware: "default"
        url_filtering: "default"
        file_blocking: "basic file blocking"
        wildfire: "default"

    - name: Create custom-url-category
      panos_type_cmd:
        provider: "{{ credentials }}"
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']/vsys
          /entry[@name='vsys1']/application-filter
        element: |
          <entry name="web-apps">
              <tagging>
                <tag>
                  <member>[Web App]</member>
                </tag>
              </tagging>
          </entry>
      register: out

    - name: Create source subnet for App1
      panos_address_object:
        provider: "{{ credentials }}"
        name: "subnet-App1"
        value: "10.0.1.0/24"
        commit: False
        state: present

    - name: Create tag for Web Access
      panos_tag_object:
        provider: "{{ credentials }}"
        name: "App1"
        color: "blue"
        comments: "Prod Environment"

    - name: Create custom-url-category
      panos_type_cmd:
        provider: "{{ credentials }}"
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /vsys/entry[@name='vsys1']
          /profiles/custom-url-category
        element: |
          <entry name="App1">
            <description>App1 custom-url-category</description>
          </entry>
      register: out

    - name: Add URL in the list
      panos_type_cmd:
        cmd: edit
        provider: "{{ credentials }}"
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /vsys/entry[@name='vsys1']
          /profiles/custom-url-category/entry[@name='App1']
        element: |
          <list>{%- for url in url_list -%}<member>{{ url }}</member>{% endfor %}</list>
          <type>URL List</type>
      register: out

    - name: Create Web Access Rule for specific App
      panos_security_rule:
        provider: "{{ credentials }}"
        rule_name: "App1 - Web Access"
        description: ""
        tag_name: ["App1", "Web Access"]
        source_zone: ["public"]
        source_ip: ["subnet-App1"]
        destination_zone: ["private"]
        destination_ip: ["any"]
        application: ["web-apps"]
        category: "App1"
        group_profile: "default"
        action: "allow"
        commit: no

    - name: Create Deny Rule for specific App
      panos_security_rule:
        provider: "{{ credentials }}"
        rule_name: "App1 - Deny"
        description: ""
        tag_name: ["App1", "Deny"]
        source_zone: ["public"]
        source_ip: ["any"]
        destination_zone: ["private"]
        destination_ip: ["any"]
        application: ["any"]
        service: ["any"]
        action: "deny"
        commit: no
